### ISSUE TITLE
Broken config for colibre

### ISSUE THREAD

**Issue by ymbahe** [SWIFTSIM/pipeline-configs#158]
It seems that one of the latest updates has broken the `colibre` configuration setup. At the end of `registration.py`, there is a reference to the recently removed `aperture_sizes` variable. Presumably all that is required is to change this to `aperture_sizes_30_100_kpc`, but it would be good if someone could verify that this is the intended behaviour.

**Comment by bwvdnbro** [comment]
Yes, this was broken in #157. The `colibre` configuration has some registration functions that are not present in `colibre-zooms` and it looks like those were not updated after the change.

**Comment by EvgeniiChaikin** [comment]
Sorry, my bad! My unit tests did not cover those two extra registration functions and I overlooked them when introducing the change in the apertures.

Thanks @ymbahe for identifying the bug and @bwvdnbro for fixing it!
