### ISSUE TITLE
Specify bins as bin size rather than number of bins

### ISSUE THREAD

**Issue by MatthieuSchaller** [SWIFTSIM/pipeline-configs#2]
In the auto-plotter, the number of bins needs to be specified. Wouldn't it make more sense to provide the bin size instead? This then means the size of the bins does not change when the data range changes (e.g. when comparing box sizes).

**Comment by JBorrow** [comment]
It's not clear this is a good idea to me; we would need to specify the bin width in log for log bins (without units) and in linear for linear binning with units...
