### ISSUE TITLE
Add a bin or something showing the 0 metallicity particles on the metal mass fraction histogram

### ISSUE THREAD

**Issue by MatthieuSchaller** [SWIFTSIM/pipeline-configs#20]
(void)

**Comment by MatthieuSchaller** [comment]
Actually, that's already done.

**Comment by EvgeniiChaikin** [comment]
@MatthieuSchaller Has this already been resolved or not? If not, I will push my tentative solution

**Comment by JBorrow** [comment]
I am going to close this as the data requested was already present.
