### ISSUE TITLE
Error messages when plotting observational data made of one single point

### ISSUE THREAD

**Issue by MatthieuSchaller** [SWIFTSIM/pipeline-configs#32]
Something must have changed on the plotting side as I now get this error message:

```
Traceback (most recent call last):
  File "./eagle-xl/scripts/stellar_mass_evolution.py", line 74, in <module>
    obs.plot_on_axes(ax)
  File "/home/matthieu/.local/lib/python3.8/site-packages/velociraptor/observations/objects.py", line 573, in plot_on_axes
    data_label = f"{self.citation} ($z={self.redshift:.1f}$)"
TypeError: unsupported format string passed to numpy.ndarray.__format__
```

I think this is related to the data set that is made of one single data point.

**Comment by JBorrow** [comment]
Well this is unexpected... I will take a look.

**Comment by JBorrow** [comment]
This is a result of the value of 'redshift' in that file being an array, not a value.

**Comment by JBorrow** [comment]
The error bars in that file are also incorrect. See https://github.com/SWIFTSIM/velociraptor-comparison-data/pull/47
