### ISSUE TITLE
Stellar ages seem to be computed or displayed incorrectly

### ISSUE THREAD

**Issue by EvgeniiChaikin** [SWIFTSIM/pipeline-configs#94]
[THIS PLOT](http://swift.dur.ac.uk/COLIBREPlots/chaikin/individual_runs/HAWK/L006N188/z1.2_20_thermalSNE_3e51_L006N0188/#1066097348338826633) is showing that the mean stellar age in several galaxies is larger than 30 Gyr (**at z=1.2**)

**Comment by JBorrow** [comment]
link is broken

**Comment by EvgeniiChaikin** [comment]
Now works!

**Comment by JBorrow** [comment]
This, I think, comes down to the borked unit system in VR. they don't use the same units for time and age...

**Comment by EvgeniiChaikin** [comment]
Indeed. Recently fixed by updating VR config. 

I close this issue
